@startuml
title Factory Method

interface Product

abstract class Creator {
  +factoryMethod() : Product
  +operation()
}

class ConcreteCreatorA
class ConcreteCreatorB

class ConcreteProductA
class ConcreteProductB

Creator <|-- ConcreteCreatorA
Creator <|-- ConcreteCreatorB

Product <|.. ConcreteProductA
Product <|.. ConcreteProductB

ConcreteCreatorA ..> ConcreteProductA : creates
ConcreteCreatorB ..> ConcreteProductB : creates
@enduml