@startuml
title Prototype

interface Prototype {
  +clone() : Prototype
}

class ConcretePrototypeA
class ConcretePrototypeB

Prototype <|.. ConcretePrototypeA
Prototype <|.. ConcretePrototypeB

class Client
Client ..> Prototype : clones
@enduml